spring.application.name=upwind_home_assignment
# The port on which spring boot application will run matches the manifest configuration for the Gmail Add-on
server.port=8080
# the secret api key for authenticating requests from the Gmail Add-on
security.api.key=assignment-secret-key